- XPCService/AppDelegate.swift
In a future version, the XPC service will behave more like an app, so let's provide a menu bar icon for the app.
> Add status bar menu

- Core/Sources/Service/GUI/RealtimeSuggestionIndicatorController.swift
- Core/Sources/Service/RealtimeSuggestionController.swift
- Core/Sources/Service/SuggestionCommandHandler/CommentBaseCommandHandler.swift
- Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
Display link is now replaced by AXObserver.
> Remove display link and tweak real-time suggestion prefetch animation

- Core/Sources/SuggestionWidget/SuggestionPanelView.swift
> Replace LazyVGrid with VStack

- Copilot for Xcode/SettingsView.swift
- Core/Sources/SuggestionWidget/SuggestionPanelView.swift
- Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
- Core/Sources/SuggestionWidget/SyntaxHighlighting.swift
- Core/Sources/XPCShared/UserDefaults.swift
- Core/Sources/XPCShared/WidgetColorScheme.swift
> Add light mode

- Copilot for Xcode/ContentView.swift
> Add linear gradient below status bar

- Core/Package.swift
- Core/Sources/OpenAIService/ChatGPTService.swift
- Core/Sources/OpenAIService/CompletionStreamAPI.swift
- Core/Sources/OpenAIService/Models.swift
- Core/Tests/OpenAIServiceTests/ChatGPTServiceFieldTests.swift
- Core/Tests/OpenAIServiceTests/ChatGPTServiceTests.swift
- TestPlan.xctestplan
Only the stream version is supported.
The prompts are currently limited to 4 messages, but since the first release will not support chats, it should be fine.
> Add ChatGPTService

- Core/Sources/Service/SuggestionPresenter/PresentInWindowSuggestionPresenter.swift
- Core/Sources/SuggestionWidget/ChatRoom.swift
- Core/Sources/SuggestionWidget/SuggestionPanelContent/ChatPanel.swift
- Core/Sources/SuggestionWidget/SuggestionPanelContent/ErrorPanel.swift
- Core/Sources/SuggestionWidget/SuggestionPanelView.swift
- Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
- Core/Sources/SuggestionWidget/WidgetView.swift
Now chat box and suggestion panel won't be racing to be displayed.
> Isolate chat and suggestion

- Core/Sources/SuggestionInjector/SuggestionInjector.swift
> fix typo in SuggestionInjector.swift

- Core/Sources/Service/SuggestionCommandHandler/PseudoCommandHandler.swift
Even if the cache is still nil.
> Never use apple script to trigger real-time suggestions

- Copilot for Xcode.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Core/Package.swift
- Core/Sources/SuggestionWidget/SuggestionPanelContent/ChatPanel.swift
- Core/Sources/SuggestionWidget/SyntaxHighlighting.swift
I am making a fork of swift-markdown-ui to add the copy button, maybe there is a better solution.
> Support syntax highlighting and copy code in chat panel

- Core/Sources/ChatPlugins/AITerminalChatPlugin.swift
- Core/Sources/ChatPlugins/AskChatGPT.swift
- Core/Sources/ChatPlugins/CallAIFunction.swift
- Core/Sources/ChatPlugins/ChatPlugin.swift
- Core/Sources/ChatPlugins/TerminalChatPlugin.swift
- Core/Sources/ChatService/ChatService.swift
- Core/Sources/OpenAIService/ChatGPTService.swift
- Core/Sources/SuggestionWidget/SuggestionPanelContent/ChatPanel.swift
- README.md
Add a chat plugin `/airun` to run a command with natural language.
> AI terminal

- Copilot for Xcode/SettingsView.swift
- Core/Sources/Preferences/Keys.swift
- Core/Sources/Preferences/PromptToCodeFeatureProvider.swift
- Core/Sources/PromptToCodeService/CopilotPromptToCodeAPI.swift
- Core/Sources/PromptToCodeService/OpenAIPromptToCodeAPI.swift
- Core/Sources/PromptToCodeService/PromptToCodeService.swift
- Core/Sources/Service/GUI/PromptToCodeProvider+Service.swift
- Core/Sources/Service/GUI/WidgetDataSource.swift
- Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
- README.md
Not functioning as good as the OpenAI implementation.
> Prompt to code with GitHub copilot

- Copilot for Xcode/App.swift
- Core/Sources/Client/AsyncXPCService.swift
- Core/Sources/Service/XPCService.swift
- Core/Sources/XPCShared/XPCServiceProtocol.swift
- EditorExtension/SourceEditorExtension.swift
https://developer.apple.com/forums/thread/682769
> Boost qos hack that doesn't seem to make any change

- Core/Sources/ChatService/ChatService.swift
- Core/Sources/Service/GUI/ChatProvider+Service.swift
- Core/Sources/SuggestionWidget/ChatProvider.swift
- Core/Sources/SuggestionWidget/SuggestionPanelContent/ChatPanel.swift
Support deleting or resending message
> Chat message manipulation

- Core/Sources/SuggestionWidget/SuggestionPanelContent/PromptToCodePanel.swift
Allow accepting when code is ready.
Reverse the scroll view so we always see the last line of the code when the bot is typing.
> Tweak prompt to code

- Copilot for Xcode/DebugView.swift
- Core/Sources/AXExtension/AXUIElement.swift
- Core/Sources/Environment/Environment.swift
- Core/Sources/Preferences/Keys.swift
- ExtensionService/AppDelegate.swift
Add alternate method to trigger command with Accessibility API
#70
> Trigger command with accessibility api

- Core/Sources/CopilotService/CopilotService.swift
- Core/Sources/Service/RealtimeSuggestionController.swift
- Core/Sources/Service/ScheduledCleaner.swift
- Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
- Core/Sources/Service/Workspace.swift
The app now implements `didCloseTextDocument` `didSaveTextDocument` `didOpenTextDocument` and `didChangeTextDocument` to support suggestions based on opened files
> Opened-file-aware suggestion

- Core/Sources/Service/ScheduledCleaner.swift
- Core/Sources/Service/Workspace.swift
Forgot to remove KVO observation
> Fix crash when remove expired workspace

- Core/Sources/Service/Workspace.swift
> Prevent duplicated `Workspace`

- ExtensionService/AppDelegate.swift
#54
Is this the right way to get the pass for the app?
I have confirmed that the application opens normally in the development environment
```swift
locateHostBundleURL(url: Bundle.main.bundleURL)
```
https://user-images.githubusercontent.com/84154073/236511759-211a2c4e-4d3a-4955-8423-20153cfd8a51.mov
> Added "Open Copilot for Xcode"

- Core/Sources/HostApp/FeatureSettings/PromptToCodeSettingsView.swift
- Core/Sources/Preferences/Keys.swift
- Core/Sources/PromptToCodeService/OpenAIPromptToCodeAPI.swift
- Core/Sources/PromptToCodeService/PromptToCodeService.swift
- The prompt now offers a step-by-step instruction for ChatGPT, so the result is more stable.
- It's now less likely to translate the selected content into your preferred human language. 
- Allow turning off generating description.
> Improve prompt of prompt to code

- Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
- Core/Sources/SuggestionWidget/WidgetView.swift
Not sure if it has anything to do with #172
> Remove order front hack

- Core/Sources/Service/ScheduledCleaner.swift
- Core/Sources/Service/Workspace.swift
#187 
Now closed tabs will be removed from the app more frequently, hopefully it helps in providing better suggestions.
> Shorter filespace life cycle

- Config.debug.xcconfig
- Core/Sources/ActiveApplicationMonitor/ActiveApplicationMonitor.swift
- Core/Sources/Service/GUI/GraphicalUserInterfaceController.swift.swift
- Core/Sources/Service/GUI/WidgetDataSource.swift
- Core/Sources/SuggestionWidget/CustomTextEditor.swift
- Core/Sources/SuggestionWidget/SuggestionPanelContent/ChatPanel.swift
- Core/Sources/SuggestionWidget/WidgetView.swift
- ExtensionService/AppDelegate.swift
- Dynamic height input box
- Use custom NSTextView based text editor for performance
- Closing windows will activate Xcode if Xcode is the previously activated app
- Change the name of global chat and file chat to avoid misunderstanding
- Support opening chat from menu bar
> Chat panel tweaks

- Core/Package.swift
- Core/Sources/AXNotificationStream/AXNotificationStream.swift
- Core/Sources/ChatContextCollector/ActiveDocumentChatContextCollector.swift
- Core/Sources/ChatContextCollector/ChatContextCollector.swift
- Core/Sources/ChatService/ChatPluginController.swift
- Core/Sources/ChatService/ChatService.swift
- Core/Sources/ChatService/DynamicContextController.swift
- Core/Sources/HostApp/CustomCommandView.swift
- Core/Sources/HostApp/FeatureSettings/ChatSettingsView.swift
- Core/Sources/Preferences/Keys.swift
- Core/Sources/Service/GUI/WidgetDataSource.swift
- Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
- Core/Sources/XcodeInspector/Helpers.swift
- Core/Sources/XcodeInspector/SourceEditor.swift
- Core/Sources/XcodeInspector/XcodeInspector.swift
- Core/Sources/XcodeInspector/XcodeWindowInspector.swift
- EditorExtension/ChatWithSelection.swift
- ExtensionService/AppDelegate.swift
- ExtensionService/ServiceDelegate.swift
- README.md
Allow chat to read the content of the active editor
> Dynamic chat with editor context

- Core/Sources/HostApp/CustomCommandView.swift
- Core/Sources/Preferences/CustomCommand.swift
- Core/Sources/Preferences/Keys.swift
- Core/Sources/PromptToCodeService/CopilotPromptToCodeAPI.swift
- Core/Sources/PromptToCodeService/OpenAIPromptToCodeAPI.swift
- Core/Sources/PromptToCodeService/PromptToCodeService.swift
- Core/Sources/Service/GUI/WidgetDataSource.swift
- Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
- README.md
- Toggle generate description for prompt to code
- Toggle Ignore extra system prompt for open chat
> More settings on custom command

- Core/Sources/ChatPlugins/TerminalChatPlugin.swift
- Core/Sources/Environment/Environment.swift
- Core/Sources/Service/FileSaveWatcher.swift
- Core/Sources/Service/OpenedFileRocoverableStorage.swift
- Core/Sources/Service/Workspace.swift
- Core/Sources/SuggestionWidget/WidgetView.swift
- Core/Tests/ServiceTests/Environment.swift
Recover opened filespaces, so that you don't have to manually switch to the file to notify the suggestion services that a file is open on launch.
> Recover opened filespaces

- Core/Sources/Service/SuggestionPresenter/PresentInWindowSuggestionPresenter.swift
- Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
- Core/Sources/SuggestionWidget/WidgetView.swift
> Fix that codeium cancellation error is presented to UI

- Core/Sources/SuggestionWidget/SuggestionPanelContent/ChatPanel.swift
> Display instructions in the chat panel

- Core/Sources/SuggestionWidget/SuggestionPanelContent/CodeBlock.swift
- Core/Sources/SuggestionWidget/SuggestionPanelContent/PromptToCodePanel.swift
> Disable LazyVStack

- Core/Sources/Service/CustomCommandTemplateProcessor.swift
- Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
- Core/Sources/XcodeInspector/SourceEditor.swift
- Tool/Sources/Preferences/Keys.swift
> Custom command inserting {{selected_code}}

- Core/Sources/ChatService/ChatPluginController.swift
- Core/Sources/SuggestionWidget/CustomTextEditor.swift
- Core/Sources/SuggestionWidget/SuggestionPanelContent/ChatPanel.swift
Add auto completion for chat plugins and scopes
> Add auto completion for chat plugins and scopes

- Core/Sources/Environment/Environment.swift
- Core/Sources/HostApp/FeatureSettings/PromptToCodeSettingsView.swift
- Core/Sources/HostApp/FeatureSettings/SuggestionSettingsView.swift
- Core/Sources/Service/SuggestionCommandHandler/PseudoCommandHandler.swift
- Core/Sources/SuggestionWidget/WidgetView.swift
- Tool/Sources/Preferences/Keys.swift
Remove acceptSuggestionWithAccessibilityAPI
> Accept suggestion automatically fallback to Accessibility API solution

- Core/Sources/HostApp/LaunchAgentManager.swift
- Core/Sources/LaunchAgentManager/LaunchAgentManager.swift
#266
But we should use SMAppService in the future
> Update launch agent template

- Copilot for Xcode.xcodeproj/project.pbxproj
- Core/Sources/AXNotificationStream/AXNotificationStream.swift
- Core/Sources/HostApp/DebugView.swift
- Core/Sources/XcodeInspector/XcodeInspector.swift
- ExtensionService/AppDelegate+Menu.swift
- ExtensionService/AppDelegate.swift
- Tool/Sources/Preferences/Keys.swift
- Remove re-observe on refresh
- Fix observation to Xcodes that are opened after the extension service
> Fix and tweak Xcode inspector

- Tool/Sources/OpenAIService/Configuration/ChatGPTConfiguration.swift
- Tool/Sources/OpenAIService/Configuration/EmbeddingConfiguration.swift
- support function calling
- fix embedding
> Azure OpenAI 2023-07-01-preview

- Core/Sources/Service/Workspace.swift
> Disallow reading large files in Filespace

- Tool/Sources/OpenAIService/ChatGPTService.swift
- Tool/Sources/OpenAIService/CompletionAPI.swift
- Tool/Sources/OpenAIService/CompletionStreamAPI.swift
> Make local models usable as an OpenAI replacement

- Core/Sources/SuggestionWidget/Styles.swift
- Core/Sources/SuggestionWidget/WidgetPositionStrategy.swift
- Core/Sources/SuggestionWidget/WidgetView.swift
> Circular widget animation when hidden

- Core/Sources/GitHubCopilotService/GitHubCopilotService.swift
> Fix freeze 341

- Core/Sources/CodeiumService/CodeiumAuthService.swift
- Core/Sources/CodeiumService/CodeiumLanguageServer.swift
- Core/Sources/HostApp/AccountSettings/CodeiumView.swift
- Tool/Sources/Preferences/Keys.swift
https://github.com/intitni/CodeiumForXcode/pull/2
> Support Codeium enterprise

- Core/Sources/SuggestionInjector/SuggestionInjector.swift
- Core/Tests/SuggestionInjectorTests/AcceptSuggestionTests.swift
Also, the test cases were incorrect..
> Fix suggestion acceptation when the suggestion lies in the middle

- Core/Sources/ChatService/CustomCommandTemplateProcessor.swift
- Core/Sources/Service/SuggestionCommandHandler/PseudoCommandHandler.swift
- Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
- README.md
> Add custom command template argument {{clipboard}}, make prompt to code support templates.

- Core/Sources/SuggestionWidget/ChatWindowView.swift
- Core/Sources/SuggestionWidget/Styles.swift
- Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
#379 
I needed some easier tasks to relax, so..
> Adjust chat window title bar UI

- Core/Sources/ChatGPTChatTab/ChatPanel.swift
#387 
Change to way to detect when the chat panel should stick to the bottom.
> Chat panel improvement

- Core/Sources/ChatGPTChatTab/ChatPanel.swift
#387 
#388 was too tricky and not that reliable..
> Track scroll event to disable pin to bottom

- Core/Sources/ChatGPTChatTab/Chat.swift
- Core/Sources/ChatGPTChatTab/ChatGPTChatTab.swift
- Core/Sources/ChatGPTChatTab/ChatPanel.swift
- Core/Sources/Service/GUI/GraphicalUserInterfaceController.swift
- Core/Sources/Service/GUI/WidgetDataSource.swift
- Core/Sources/Service/GlobalShortcutManager.swift
- Core/Sources/Service/Service.swift
- Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
- Core/Sources/SuggestionWidget/FeatureReducers/ChatPanelFeature.swift
- Core/Sources/SuggestionWidget/FeatureReducers/PanelFeature.swift
- Core/Sources/SuggestionWidget/FeatureReducers/PromptToCode.swift
- Core/Sources/SuggestionWidget/FeatureReducers/PromptToCodeGroup.swift
- Core/Sources/SuggestionWidget/FeatureReducers/WidgetFeature.swift
- Core/Sources/SuggestionWidget/ModuleDependency.swift
- Core/Sources/SuggestionWidget/SharedPanelView.swift
- Core/Sources/SuggestionWidget/SuggestionPanelContent/PromptToCodePanel.swift
- Tool/Package.swift
- Tool/Sources/AppActivator/AppActivator.swift
- Tool/Sources/ChatTab/ChatTab.swift
- Tool/Sources/ChatTab/ChatTabItem.swift
- Tool/Sources/Environment/Environment.swift
- Tool/Sources/FocusedCodeFinder/FocusedCodeFinder.swift
- Tool/Sources/XcodeInspector/XcodeInspector.swift
> Active extension app when using hotkey to show widget

- Tool/Sources/OpenAIService/ChatGPTService.swift
> Ignore trunk id from stream reply

- Core/Sources/PromptToCodeService/OpenAIPromptToCodeService.swift
- Tool/Sources/CodeiumService/CodeiumService.swift
- Tool/Sources/FocusedCodeFinder/ObjectiveC/ObjectiveCCodeFinder.swift
- Tool/Sources/FocusedCodeFinder/Swift/SwiftFocusedCodeFinder.swift
- Tool/Sources/GitIgnoreCheck/GitIgnoreCheck.swift
- Tool/Sources/WorkspaceSuggestionService/Filespace+SuggestionService.swift
- Tool/Sources/XcodeInspector/SourceEditor.swift
> Support various line endings

- Core/Sources/SuggestionWidget/ChatWindowView.swift
- Core/Sources/SuggestionWidget/FeatureReducers/WidgetFeature.swift
- Core/Sources/SuggestionWidget/ModuleDependency.swift
- Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
> Chat window with normal title bar

- Core/Sources/SuggestionWidget/FeatureReducers/WidgetFeature.swift
> Fix that detached chat window size and position was reset when hidden

- Core/Sources/Service/RealtimeSuggestionController.swift
- Core/Sources/SuggestionWidget/FeatureReducers/WidgetFeature.swift
- Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
- Tool/Package.swift
- Tool/Sources/AXNotificationStream/AXNotificationStream.swift
- Tool/Sources/Logger/Logger.swift
- Tool/Sources/XcodeInspector/Apps/XcodeAppInstanceInspector.swift
- Tool/Sources/XcodeInspector/SourceEditor.swift
- Tool/Sources/XcodeInspector/XcodeInspector.swift
- Tool/Sources/XcodeInspector/XcodeWindowInspector.swift
> Handle AXNotification in one place

- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEdit.swift
- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEditView.swift
- Core/Sources/HostApp/AccountSettings/EmbeddingModelManagement/EmbeddingModelEdit.swift
- Core/Sources/HostApp/AccountSettings/EmbeddingModelManagement/EmbeddingModelEditView.swift
- Core/Sources/HostApp/AccountSettings/SharedModelManagement/BaseURLPicker.swift
- Core/Sources/HostApp/AccountSettings/SharedModelManagement/BaseURLSelection.swift
- Tool/Sources/AIModel/ChatModel.swift
- Tool/Sources/AIModel/EmbeddingModel.swift
- Tool/Sources/Preferences/Keys.swift
Add compatibility with Perplexity.ai API's distinct endpoint structure.
https://api.perplexity.ai/chat/completions
> Modify baseURL to full path

- Core/Sources/ChatContextCollectors/WebChatContextCollector/WebChatContextCollector.swift
- Core/Sources/ChatGPTChatTab/Chat.swift
- Core/Sources/ChatGPTChatTab/ChatPanel.swift
- Core/Sources/ChatService/ChatService.swift
- Core/Sources/ChatService/ContextAwareAutoManagedChatGPTMemory.swift
- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEdit.swift
- Core/Sources/HostApp/AccountSettings/EmbeddingModelManagement/EmbeddingModelEdit.swift
- Tool/Sources/AIModel/ChatModel.swift
- Tool/Sources/AIModel/EmbeddingModel.swift
- Tool/Sources/LangChain/Chains/LLMChain.swift
- Tool/Sources/LangChain/Chains/RefineDocumentChain.swift
- Tool/Sources/LangChain/Chains/RelevantInformationExtractionChain.swift
- Tool/Sources/LangChain/Chains/StructuredOutputChatModelChain.swift
- Tool/Sources/OpenAIService/APIs/ChatCompletionsAPIDefinition.swift
- Tool/Sources/OpenAIService/APIs/GoogleAIChatCompletionsService.swift
- Tool/Sources/OpenAIService/APIs/OlamaChatCompletionsService.swift
- Tool/Sources/OpenAIService/APIs/OpenAIChatCompletionsService.swift
- Tool/Sources/OpenAIService/APIs/OpenAIEmbeddingService.swift
- Tool/Sources/OpenAIService/ChatGPTService.swift
- Tool/Sources/OpenAIService/FucntionCall/ChatGPTFunction.swift
- Tool/Sources/OpenAIService/Memory/AutoManagedChatGPTMemoryStrategy/AutoManagedChatGPTMemoryOpenAIStrategy.swift
- Tool/Sources/OpenAIService/Memory/ChatGPTMemory.swift
- Tool/Sources/OpenAIService/Models.swift
- Tool/Tests/OpenAIServiceTests/ChatGPTStreamTests.swift
- Tool/Tests/OpenAIServiceTests/ReformatPromptToBeGoogleAICompatibleTests.swift
Update to use tool_call instead of function_call #444 
Plus some refactoring.
> Update OpenAI chat completions api to latest format

- Core/Sources/SuggestionWidget/FeatureReducers/PanelFeature.swift
- Core/Sources/SuggestionWidget/FeatureReducers/WidgetFeature.swift
- Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
- Core/Sources/SuggestionWidget/WidgetWindowsController.swift
> Fix that some commands will dismiss suggestions

- Core/Sources/HostApp/DebugView.swift
- Tool/Package.swift
- Tool/Sources/AXNotificationStream/AXNotificationStream.swift
- Tool/Sources/Preferences/Keys.swift
Lets see if it can make the app perform better
> AXNotification with global background thread and default mode

- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEdit.swift
- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEditView.swift
- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelManagement.swift
- Core/Sources/HostApp/AccountSettings/EmbeddingModelManagement/EmbeddingModelEdit.swift
- Core/Sources/HostApp/AccountSettings/EmbeddingModelManagement/EmbeddingModelEditView.swift
- Core/Sources/HostApp/HandleToast.swift
- Core/Sources/HostApp/TabContainer.swift
- Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
- Tool/Sources/AIModel/ChatModel.swift
- Tool/Sources/OpenAIService/APIs/ClaudeChatCompletionsService.swift
- Tool/Sources/OpenAIService/APIs/OpenAIChatCompletionsService.swift
- Tool/Sources/OpenAIService/ChatGPTService.swift
- Tool/Sources/Toast/Toast.swift
> Add Claude support

- Tool/Sources/OpenAIService/APIs/ClaudeChatCompletionsService.swift
Claude doesn't support conjunct messages to have the same role.
> Join same-role messages for claude models

- Tool/Sources/GitHubCopilotService/GitHubCopilotService.swift
#477 Previously it only shows that it's a language server error.
> Display GitHub Copilot language server error description in the host app

- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEditView.swift
- Tool/Package.swift
- Tool/Sources/AIModel/ChatModel.swift
- Tool/Sources/OpenAIService/APIs/GoogleAIChatCompletionsService.swift
- Tool/Sources/OpenAIService/ChatGPTService.swift
> Google Generative AI custom base url

- Core/Sources/HostApp/FeatureSettings/ChatSettingsView.swift
- Core/Sources/SuggestionWidget/ChatPanelWindow.swift
- Core/Sources/SuggestionWidget/ChatWindowView.swift
- Core/Sources/SuggestionWidget/FeatureReducers/ChatPanelFeature.swift
- Core/Sources/SuggestionWidget/FeatureReducers/WidgetFeature.swift
- Core/Sources/SuggestionWidget/WidgetWindowsController.swift
- Tool/Sources/Preferences/Keys.swift
> Disable float on top when the chat panel is detached

- Tool/Sources/OpenAIService/APIs/OpenAIChatCompletionsService.swift
- Tool/Sources/OpenAIService/APIs/OpenAIEmbeddingService.swift
> Add title field for OpenRouter requests

- Core/Sources/HostApp/AccountSettings/GitHubCopilotView.swift
- Tool/Package.swift
- Tool/Sources/GitHubCopilotService/LanguageServer/GitHubCopilotService.swift
- Tool/Sources/GitHubCopilotService/Resources/load-self-signed-cert.js
- Tool/Sources/Preferences/Keys.swift
> GitHub copilot self signed certificate hack

- Core/Sources/SuggestionWidget/ChatPanelWindow.swift
- Core/Sources/SuggestionWidget/WidgetWindowsController.swift
Fix that widgets are not visible in fullscreen mode.
Also seems to fix #468
> macOS 15 hot fix

- Core/Sources/SuggestionWidget/ChatPanelWindow.swift
- Core/Sources/SuggestionWidget/FeatureReducers/WidgetFeature.swift
- Core/Sources/SuggestionWidget/WidgetWindowsController.swift
- Tool/Sources/AXExtension/AXUIElement.swift
> Tweak collection behavior when Xcode is in fullscreen

- Core/Sources/Service/DependencyUpdater.swift
- Tool/Sources/CodeiumService/CodeiumInstallationManager.swift
- Tool/Sources/GitHubCopilotService/GitHubCopilotInstallationManager.swift
- Tool/Sources/Preferences/Keys.swift
> Added Support for Automatic and Custom Enterprise Language Server Updates as well as fixing versioning issues

- Core/Sources/ChatGPTChatTab/Chat.swift
- Core/Sources/ChatGPTChatTab/ChatPanel.swift
- Core/Sources/ChatGPTChatTab/Views/BotMessage.swift
- Core/Sources/ChatGPTChatTab/Views/ThemedMarkdownText.swift
- Core/Sources/ChatGPTChatTab/Views/UserMessage.swift
Hopefully the scroll is smoother
> Prevent reevaluating markdown content on scroll

- Tool/Package.swift
- Tool/Sources/GitHubCopilotService/LanguageServer/GitHubCopilotInstallationManager.swift
- Tool/Sources/GitHubCopilotService/LanguageServer/GitHubCopilotService.swift
- Tool/Sources/GitHubCopilotService/Resources/load-self-signed-cert-1.34.0.js
> Bump Copilot.vim to 1.37.0

- Core/Sources/HostApp/FeatureSettings/Chat/ChatSettingsGeneralSectionView.swift
- Tool/Sources/CodeiumService/ChatTab/CodeiumChatTab.swift
- Tool/Sources/CodeiumService/Services/CodeiumService.swift
Cleaned names and added some url params
> Cleaned up codeium

- Core/Sources/HostApp/General.swift
- Core/Sources/HostApp/GeneralView.swift
- Core/Sources/HostApp/HostApp.swift
- Core/Sources/HostApp/LaunchAgentManager.swift
- Core/Sources/LaunchAgentManager/LaunchAgentManager.swift
#562 
If the app is in folders other than /Applications, it will install the launch agents with the old method to ~/Library/Launch Agents.
> Support installing to other folders

- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEdit.swift
- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEditView.swift
- Tool/Sources/AIModel/ChatModel.swift
- Tool/Sources/OpenAIService/APIs/OpenAIChatCompletionsService.swift
> Add OpenAI-Project and OpenAI-Organization

- Tool/Sources/GitHubCopilotService/LanguageServer/GitHubCopilotInstallationManager.swift
> Bump GitHub copilot to 1.40.0

- Tool/Sources/AXExtension/AXUIElement.swift
- Tool/Sources/XcodeInspector/Apps/XcodeAppInstanceInspector.swift
Fix that searching for tabs in Xcode cause Xcode to have performance issue #569
> Fix that searching for tabs in Xcode cause Xcode to have performance issue

- Tool/Sources/GitHubCopilotService/LanguageServer/GitHubCopilotRequest.swift
- Tool/Sources/GitHubCopilotService/Services/GitHubCopilotChatService.swift
> Support setting language to GitHub Copilot chat

- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEdit.swift
- Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEditView.swift
- Tool/Sources/AIModel/ChatModel.swift
- Tool/Sources/OpenAIService/APIs/OpenAIChatCompletionsService.swift
> Fix OpenAI compatible API supports for APIs that don't support multi-part message content
