Copilot for Xcode.xcodeproj/project.pbxproj
Core/Sources/Client/AsyncXPCService.swift
Core/Sources/Service/AutoTrigger.swift
Core/Sources/Service/XPCService.swift
Core/Sources/XPCShared/XPCServiceProtocol.swift
DEVELOPMENT.md
EditorExtension/PrefetchSuggestionsCommand.swift
EditorExtension/SourceEditorExtension.swift
README.md

Added a new command "Prefetch Suggestions". It will return immediately and request suggestions asynchronously. Once suggestions are fetched, it will call the command "Real-time Suggestions" to present the suggestions.
The prefetch command doesn't seem to block the editor, so the debounce threshold is lowered to 2 seconds. (maybe in the future it can be customized)

Tweak real-time suggestion with a immediately-returned prefetch command

---

Core/Sources/Client/XPCService.swift
Core/Sources/Service/AutoTrigger.swift
Core/Sources/Service/CGEventObserver.swift
Core/Sources/Service/Environment.swift
Core/Sources/Service/Workspace.swift
Core/Sources/Service/XPCService.swift
Core/Sources/XPCShared/UserDefaults.swift
README.md
XPCService/main.swift

In the previous versions the states are not persisted, so users will have to manually turn them back on again when the XPCService is restarted.
Now they are persisted in UserDefaults. And the `AutoTrigger` will now start if Xcode is running and stop when Xcode is terminated.

Persist real-time suggestions state

---

Core/Sources/CopilotService/CopilotService.swift
Core/Sources/Service/Workspace.swift
Core/Sources/SuggestionInjector/SuggestionInjector.swift
Core/Tests/CopilotServiceTests/FetchSuggestionsTests.swift
Core/Tests/SuggestionInjectorTests/ProposeSuggestionTests.swift

Fixes #15 
The issue is that empty suggestions are not ignored. Unlike VSCode, where the user can tap enter to accept a suggestion, it feels more natural to just ignore these suggestions in Copilot for Xcode. 
This PR also fixes that suggestion comments may be inserted into the wrong line.

Ignore empty suggestions and fix wrong suggestion comment positions

---

Copilot for Xcode.xcodeproj/project.pbxproj
Copilot for Xcode.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Copilot for Xcode/LaunchAgentManager.swift
Copilot for Xcode/LaunchAgentView.swift
Core/Package.swift
Core/Sources/FileChangeChecker/FileChangeChecker.swift
Core/Sources/LaunchAgentManager/LaunchAgentManager.swift
Helper/ReloadLaunchAgent.swift
Helper/main.swift
README.md
XPCService/main.swift

Whenever Xcode or Copilot for Xcode is launched, The XPC Service will check if the executable is changed by comparing the md5 of the file.
If changed, it will restart the launch agent.

Automatically restart XPC service on updates

---

Core/Sources/Service/GUI/GraphicalUserInterfaceController.swift.swift
Core/Sources/Service/RealtimeSuggestionController.swift
Core/Sources/Service/SuggestionCommandHandler/CommentBaseCommandHandler.swift
Core/Sources/Service/SuggestionCommandHandler/PseudoCommandHandler.swift
Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
Core/Sources/Service/Workspace.swift
Core/Sources/SuggestionWidget/SuggestionPanelView.swift
Core/Sources/SuggestionWidget/SuggestionWidgetController.swift

The prefetch suggestions command may still cause the editor to become blocked, so I have implemented a temporary workaround.
Instead of directly calling the command using Apple Script, it now first verifies whether there is sufficient information to create an `EditorContent`. If there is, it will call the other command handlers directly; otherwise, it will fall back to using Apple Script.
The necessary information can be retrieved either from the cache of another command or through the Accessibility API.
Another advantage of this approach is that the `PseudoCommandHandler` can also be utilized in the suggestion panel buttons.

Add PseudoCommandHandler

---

Copilot for Xcode.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Core/Package.swift
Core/Sources/CopilotService/LanguageIdentifierFromFilePath.swift
Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
Core/Sources/Service/SuggestionPresenter/PresentInWindowSuggestionPresenter.swift
Core/Sources/Service/Workspace.swift
Core/Sources/SuggestionWidget/SuggestionPanelView.swift
Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
Core/Sources/SuggestionWidget/WidgetView.swift

Splash is good at Swift, but it's not providing builtin support for other languages. Highlightr uses highlight.js, which is terrible in highlighting Swift. Hope someone can make a wrapper for prism.js.
So Splash will be used for Swift, and Highlightr will be used for other languages. The color scheme used is One Dark.

Add syntax highlighting

---

Core/Sources/SuggestionWidget/SyntaxHighlighting.swift

`highlight.js` uses `objectivec` as the identifier for Objective-C

Fix syntax highlighting for objc

---

README.md

Provides more detailed information on how to set up the LaunchAgent plist file manually

Add guidance for manual LaunchAgent setup

---

Core/Sources/SuggestionWidget/SuggestionPanelContent/ChatPanel.swift
Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
Core/Sources/SuggestionWidget/TabView.swift

- Adjust UI of chat panel
- Better support for Monterey (SF Symbols and TextEditor) #89 
- Automatically activate chat panel text field on creation
- Tweak activationPolicy change (maybe relevant to #95)
- Prevent chat panel from being hidden when something changed in Xcode but Xcode is not active (may be relevant to #92)

Tweak chat box behavior

---

Core/Sources/Service/RealtimeSuggestionController.swift
Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift

In previous versions, the real-time suggestion has to run via Apple Script at least once to cache some information for later use. That will block the editor and dismiss the completion panel.
Now we trigger the unused "Real-time Suggestions" command when the focused element changes to pre-cache the info.

Cache filespace info automatically on file change

---

Copilot for Xcode/SettingsView.swift
Core/Sources/Preferences/Keys.swift
Core/Sources/Service/GUI/GraphicalUserInterfaceController.swift.swift
Core/Sources/Service/SuggestionCommandHandler/PseudoCommandHandler.swift
Core/Sources/Service/SuggestionPresenter/PresentInWindowSuggestionPresenter.swift
Core/Sources/Service/Workspace.swift

A workaround for #70 
But it has some drawbacks:
- The change is not in-place, if a user undos a acceptation, the whole file will be selected and the editor will scroll to top.
- Calculation the selected range is too cumbersome so I just restored the old one before the acceptation.

Accept suggestion via Accessibility API in widget

---

Core/Sources/CopilotService/CopilotRequest.swift
Core/Sources/CopilotService/CopilotService.swift
Core/Sources/CopilotService/LanguageIdentifierFromFilePath.swift
Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
Core/Sources/Service/Workspace.swift

In previous releases, GitHub Copilot won't generate suggestions for languages not listed in enum `LanguageIdentifier`, we are removing this limitation.
If a language identifier is not detected, we will just use it's path extension as the language

Support more languages

---

Core/Sources/Service/RealtimeSuggestionController.swift
Core/Sources/Service/SuggestionCommandHandler/PseudoCommandHandler.swift
README.md

Looks like the current caching mechanism may disable the source extension sometimes. I have no evidence that this is the cause, but I just can't think of another one.
We have rollback to use menu bar command to fetch real-time suggestion when needed, but added new a rule that it will not use this method when the completion panel is displayed.

Update suggestion caching mechanism

---

Core/Sources/CopilotModel/ExportedFromLSP.swift
Core/Sources/PromptToCodeService/PromptToCodeService.swift
Core/Sources/Service/GUI/PromptToCodeProvider+Service.swift
Core/Sources/Service/SuggestionCommandHandler/CommentBaseCommandHandler.swift
Core/Sources/Service/SuggestionCommandHandler/PseudoCommandHandler.swift
Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
Core/Sources/Service/SuggestionPresenter/PresentInCommentSuggestionPresenter.swift
Core/Sources/SuggestionWidget/PromptToCodeProvider.swift
Core/Sources/SuggestionWidget/SuggestionPanelContent/CodeBlock.swift
Core/Sources/SuggestionWidget/SuggestionPanelContent/PromptToCodePanel.swift
Core/Sources/XPCShared/Models.swift
EditorExtension/Helpers.swift

- Make the prompt to code window stays after accepting when continuous mode is on.
- Add a key binding to the accept button.
- Fix extracting selection when the whole file is selected.
- When the selection contains multiple line, force the first line to start with col 0.

Continuous prompt to code

---

Copilot for Xcode/CustomCommandView.swift
Core/Sources/Client/AsyncXPCService.swift
Core/Sources/Preferences/CustomCommand.swift
Core/Sources/Preferences/Keys.swift
Core/Sources/Service/GUI/GraphicalUserInterfaceController.swift.swift
Core/Sources/Service/SuggestionCommandHandler/CommentBaseCommandHandler.swift
Core/Sources/Service/SuggestionCommandHandler/PseudoCommandHandler.swift
Core/Sources/Service/SuggestionCommandHandler/SuggestionCommandHandler.swift
Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift
Core/Sources/Service/XPCService.swift
Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
Core/Sources/SuggestionWidget/WidgetView.swift
Core/Sources/XPCShared/XPCServiceProtocol.swift
EditorExtension/CustomCommand.swift
EditorExtension/SourceEditorExtension.swift

Added a `commandId` field to `CustomCommand`, which should be a UUID string. For old commands that don't have an id, they will use the SHA1 of the name as id, which was used in 0.13.2, to avoid re-configuration of keybindings.

Add id to CustomCommand

---

Core/Sources/GitHubCopilotService/GitHubCopilotInstallationManager.swift
Core/Sources/HostApp/AccountSettings/CopilotView.swift

Looks like the install(copy) at launch was not working for some users. It should be better to give them an install button.
But actually the language server is still embedded inside the app.

GitHub Copilot installation manager

---

Core/Sources/CodeiumService/CodeiumService.swift
Core/Sources/CodeiumService/OpendDocumentPool.swift
Core/Sources/GitHubCopilotService/GitHubCopilotService.swift
Core/Sources/Service/RealtimeSuggestionController.swift
Core/Sources/Service/SuggestionCommandHandler/PseudoCommandHandler.swift
Core/Sources/Service/Workspace.swift
Core/Sources/Service/XPCService.swift
Core/Sources/SuggestionInjector/SuggestionInjector.swift
Core/Sources/SuggestionService/CodeiumSuggestionProvider.swift
Core/Sources/SuggestionService/GitHubCopilotSuggestionProvider.swift
Core/Sources/SuggestionService/SuggestionService.swift
Core/Sources/XcodeInspector/SourceEditor.swift
Core/Tests/ServiceTests/Environment.swift
Core/Tests/SuggestionInjectorTests/AcceptSuggestionTests.swift
README.md

- Invalidate suggestions when they are no longer relevant to the source code and the text cursor’s current position. #197 
- Keep the suggestion when user is typing as the suggestion suggests.
- Remove the request cancellation when users press arrow keys or click with the mouse.
- Simpler implementation of request cancellation.

Real time suggestion tweak

---

Core/Sources/SuggestionWidget/SuggestionWidgetController.swift

#269 
Reproduce the bug my turning on group windows by application in Mission Control

Make full screen detector transient so it won't show up in Mission Control 

---

Core/Sources/SuggestionInjector/SuggestionInjector.swift
Core/Tests/SuggestionInjectorTests/AcceptSuggestionTests.swift

For example: 
Suggestion for `print(` -> `print("hello world")`. If user keeps typing, Xcode will auto complete the code into `print("")`.
The suggestion is still valid, but accepting it will result in `print("hello world")")`

Fix accepting suggestion in special case

---

Core/Sources/ChatContextCollectors/WebChatContextCollector/QueryWebsiteFunction.swift
Playground.playground/Pages/RetrievalQAChain.xcplaygroundpage/Contents.swift
Playground.playground/Pages/RetrievalQAChain.xcplaygroundpage/timeline.xctimeline
Tool/Sources/LangChain/Agent.swift
Tool/Sources/LangChain/Callback.swift
Tool/Sources/LangChain/Chain.swift
Tool/Sources/LangChain/Chains/RefineDocumentChain.swift
Tool/Sources/LangChain/Chains/RelevantInformationExtractionChain.swift
Tool/Sources/LangChain/Chains/RetrievalQA.swift
Tool/Sources/LangChain/ChatModel/ChatModel.swift

Now `QAInformationRetrievalChain` will only gather the needed information, and returns it as the function call result.
`RelevantInformationExtractionChain` will be used to gather information from each chunk, and they can work simultaneously , so it will be faster than the old `RefineDocumentChain`.

Update retrieval chain to only gather information

---

Core/Sources/ChatGPTChatTab/ChatContextMenu.swift
Core/Sources/ChatGPTChatTab/ChatGPTChatTab.swift
Core/Sources/ChatService/ChatService.swift
Core/Sources/Service/GUI/ChatTabFactory.swift
Core/Sources/Service/GUI/GraphicalUserInterfaceController.swift
Core/Sources/SuggestionWidget/ChatWindowView.swift
Core/Sources/SuggestionWidget/FeatureReducers/ChatPanelFeature.swift
Core/Sources/SuggestionWidget/FeatureReducers/WidgetFeature.swift
Core/Sources/SuggestionWidget/ModuleDependency.swift
Core/Sources/SuggestionWidget/SuggestionWidgetController.swift
TestPlan.xctestplan
Tool/Sources/ChatTab/ChatTab.swift
Tool/Sources/ChatTab/ChatTabItem.swift
Tool/Sources/ChatTab/ChatTabPool.swift
Tool/Sources/OpenAIService/Configuration/UserPreferenceChatGPTConfiguration.swift
Tool/Sources/Preferences/Types/ChatFeatureProvider.swift

Add ChatTabPool. The store won't hold the actual chat tab classes any more.
Add ChatTabItem to allow chat tabs to send actions to the store.
Add ChatTabPersistent to provide persistence for tabs.

Persisted chat

---

Core/Sources/ChatService/DynamicContextController.swift
Tool/Sources/OpenAIService/Memory/AutoManagedChatGPTMemory.swift

#385 
Sometimes, LLM can't find the code in the top most system prompt, so I am moving the system prompts generated by context collectors to right above the latest message.
This is what GitHub Copilot Chat is doing, so I think it should make it work better.

Adjust position of context system prompt

---

Tool/Sources/CodeiumService/CodeiumAuthService.swift

Appears Codeium register user path is out of date. This PR updates path to match what is in other plugins like this: https://github.com/Exafunction/codeium.vim/blob/fd440cd718742daab162241c5bd5857cd92f5f72/autoload/codeium/command.vim#L88
Thank you.

Update Codeium enterprise register user path

---

Core/Sources/HostApp/AccountSettings/GitHubCopilotView.swift
Core/Sources/Service/XPCService.swift
Tool/Sources/AsyncPassthroughSubject/AsyncPassthroughSubject.swift
Tool/Sources/GitHubCopilotService/GitHubCopilotInstallationManager.swift
Tool/Sources/GitHubCopilotService/GitHubCopilotRequest.swift
Tool/Sources/GitHubCopilotService/GitHubCopilotService.swift
Tool/Sources/OpenAIService/Debug/Debug.swift
Tool/Sources/Preferences/Keys.swift
Tool/Sources/XcodeInspector/XcodeInspector.swift

#440 
https://github.com/intitni/CopilotForXcode/releases/download/0.30.5.beta/Copilot.for.Xcode.github.copilot.enterprise.2.app.zip

Support GitHub Copilot enterprise

---

Tool/Sources/OpenAIService/ChatGPTService.swift

Just in case any service doesn't specify a role in the response #449

Add a default role to stream response

---

Core/Sources/Service/SuggestionCommandHandler/WindowBaseCommandHandler.swift

Back in the day we were using commands to generate real-time suggestions. But we don't need it anymore. #454

Remove snapshot check fetching suggestion manually

---

Tool/Sources/CodeiumService/CodeiumInstallationManager.swift

1.8.9 doesn't have a macOS version, so 1.8.8 is the latest

Bump codeium language server 1.8.8

---

Core/Sources/HostApp/AccountSettings/CodeiumView.swift
Tool/Sources/CodeiumService/CodeiumWorkspacePlugin.swift
Tool/Sources/CodeiumService/LanguageServer/CodeiumInstallationManager.swift
Tool/Sources/CodeiumService/LanguageServer/CodeiumLanguageServer.swift
Tool/Sources/CodeiumService/Services/CodeiumService.swift
Tool/Sources/Preferences/Keys.swift

- Added Support to extract dir from workspace, before we were just analyzing the workspace and not the actual repos in the workspace for indexing

Added Indexing Changes for Codeium

---

Core/Package.swift
Tool/Package.swift

Compile error in the latest version's Xcode 16.

fix: update version of swift-markdown-ui and TCA to fix compile error  of swift 6

---

Tool/Sources/AppActivator/AppActivator.swift
Tool/Sources/XcodeInspector/XcodeInspector+TriggerCommand.swift

Looks like setting frontmost to true brings all window to the front. The only solution is to bring back `.activate()` and fallback to `isFrontmost` when it fails for some users.
Another tweak is that we will check if the app is already frontmost before activating the app.
#616

Fix that activate app brings all windows to front

---

Core/Sources/HostApp/AccountSettings/ChatModelManagement/ChatModelEditView.swift
Tool/Sources/OpenAIService/APIs/OlamaChatCompletionsService.swift

Using Ollama through OpenWebUI requires clients to send an API token with their requests in order to interact with a model. OpenWebUI's documentation on the topic can be found [here](https://docs.openwebui.com/getting-started/api-endpoints#-retrieve-all-models).
- I've added the `ApiKeyNamePicker` to the `OllamaForm`.
- I've implemented adding the `Bearer` header to the URL requests in `OllamaChatCompletionsService`.

Authenticate when sending requests to Ollama
